import { WeatherConditionInfo } from '../types';

export const WMO_CODES: Record<number, WeatherConditionInfo> = {
  0: {
    label: 'Clear Sky',
    description: 'Bright and clear skies',
    iconName: 'Sun',
    bgGradientDay: 'from-amber-400 via-sky-400 to-blue-600',
    bgGradientNight: 'from-slate-900 via-indigo-950 to-slate-900',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-amber-300',
    isRainy: false,
    isSnowy: false,
    isSevere: false,
  },
  1: {
    label: 'Mainly Clear',
    description: 'Mostly clear with faint clouds',
    iconName: 'SunDim',
    bgGradientDay: 'from-sky-400 via-blue-500 to-indigo-600',
    bgGradientNight: 'from-slate-900 via-slate-800 to-indigo-950',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-sky-200',
    isRainy: false,
    isSnowy: false,
    isSevere: false,
  },
  2: {
    label: 'Partly Cloudy',
    description: 'Scattered clouds passing over',
    iconName: 'CloudSun',
    bgGradientDay: 'from-sky-400 via-blue-600 to-slate-700',
    bgGradientNight: 'from-slate-900 via-slate-800 to-slate-900',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-sky-100',
    isRainy: false,
    isSnowy: false,
    isSevere: false,
  },
  3: {
    label: 'Overcast',
    description: 'Dense cloud coverage',
    iconName: 'Cloud',
    bgGradientDay: 'from-slate-500 via-slate-600 to-slate-800',
    bgGradientNight: 'from-slate-950 via-slate-900 to-slate-950',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-slate-200',
    isRainy: false,
    isSnowy: false,
    isSevere: false,
  },
  45: {
    label: 'Fog',
    description: 'Low visibility due to fog',
    iconName: 'CloudFog',
    bgGradientDay: 'from-slate-400 via-slate-500 to-slate-700',
    bgGradientNight: 'from-slate-900 via-slate-900 to-zinc-900',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-slate-300',
    isRainy: false,
    isSnowy: false,
    isSevere: false,
  },
  48: {
    label: 'Depositing Rime Fog',
    description: 'Freezing fog forming frost',
    iconName: 'CloudFog',
    bgGradientDay: 'from-slate-400 via-cyan-700 to-slate-800',
    bgGradientNight: 'from-slate-900 via-cyan-950 to-slate-950',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-cyan-200',
    isRainy: false,
    isSnowy: true,
    isSevere: false,
  },
  51: {
    label: 'Light Drizzle',
    description: 'Fine, gentle rain drops',
    iconName: 'CloudDrizzle',
    bgGradientDay: 'from-blue-500 via-slate-600 to-indigo-800',
    bgGradientNight: 'from-slate-900 via-blue-950 to-slate-950',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-sky-300',
    isRainy: true,
    isSnowy: false,
    isSevere: false,
  },
  53: {
    label: 'Moderate Drizzle',
    description: 'Steady drizzle outdoors',
    iconName: 'CloudDrizzle',
    bgGradientDay: 'from-blue-600 via-slate-700 to-indigo-900',
    bgGradientNight: 'from-slate-950 via-slate-900 to-blue-950',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-sky-300',
    isRainy: true,
    isSnowy: false,
    isSevere: false,
  },
  55: {
    label: 'Dense Drizzle',
    description: 'Heavy damp drizzle',
    iconName: 'CloudDrizzle',
    bgGradientDay: 'from-slate-600 via-blue-700 to-slate-900',
    bgGradientNight: 'from-slate-950 via-blue-950 to-slate-900',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-sky-300',
    isRainy: true,
    isSnowy: false,
    isSevere: false,
  },
  56: {
    label: 'Light Freezing Drizzle',
    description: 'Cold drizzle creating slippery roads',
    iconName: 'CloudHail',
    bgGradientDay: 'from-slate-600 via-cyan-700 to-slate-900',
    bgGradientNight: 'from-slate-950 via-cyan-950 to-slate-900',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-cyan-300',
    isRainy: true,
    isSnowy: true,
    isSevere: true,
  },
  57: {
    label: 'Dense Freezing Drizzle',
    description: 'Hazardous icy drizzle',
    iconName: 'CloudHail',
    bgGradientDay: 'from-slate-700 via-cyan-800 to-slate-950',
    bgGradientNight: 'from-slate-950 via-cyan-950 to-slate-950',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-cyan-300',
    isRainy: true,
    isSnowy: true,
    isSevere: true,
  },
  61: {
    label: 'Slight Rain',
    description: 'Light rainfall',
    iconName: 'CloudRain',
    bgGradientDay: 'from-blue-600 via-slate-700 to-indigo-900',
    bgGradientNight: 'from-slate-900 via-blue-950 to-slate-950',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-sky-300',
    isRainy: true,
    isSnowy: false,
    isSevere: false,
  },
  63: {
    label: 'Moderate Rain',
    description: 'Continuous moderate rain',
    iconName: 'CloudRain',
    bgGradientDay: 'from-slate-700 via-blue-800 to-slate-900',
    bgGradientNight: 'from-slate-950 via-slate-900 to-indigo-950',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-sky-300',
    isRainy: true,
    isSnowy: false,
    isSevere: false,
  },
  65: {
    label: 'Heavy Rain',
    description: 'Pouring heavy rain',
    iconName: 'CloudRainWind',
    bgGradientDay: 'from-slate-800 via-blue-900 to-slate-950',
    bgGradientNight: 'from-slate-950 via-blue-950 to-black',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-blue-300',
    isRainy: true,
    isSnowy: false,
    isSevere: true,
  },
  66: {
    label: 'Freezing Rain',
    description: 'Icy precipitation',
    iconName: 'CloudHail',
    bgGradientDay: 'from-slate-700 via-cyan-800 to-slate-900',
    bgGradientNight: 'from-slate-950 via-cyan-950 to-black',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-cyan-300',
    isRainy: true,
    isSnowy: true,
    isSevere: true,
  },
  67: {
    label: 'Heavy Freezing Rain',
    description: 'Hazardous ice accumulation',
    iconName: 'CloudHail',
    bgGradientDay: 'from-slate-800 via-cyan-900 to-black',
    bgGradientNight: 'from-slate-950 via-cyan-950 to-black',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-cyan-300',
    isRainy: true,
    isSnowy: true,
    isSevere: true,
  },
  71: {
    label: 'Slight Snow',
    description: 'Light snowfall flakes',
    iconName: 'CloudSnow',
    bgGradientDay: 'from-slate-500 via-indigo-600 to-cyan-800',
    bgGradientNight: 'from-slate-900 via-indigo-950 to-slate-950',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-indigo-200',
    isRainy: false,
    isSnowy: true,
    isSevere: false,
  },
  73: {
    label: 'Moderate Snow',
    description: 'Steady snow shower',
    iconName: 'CloudSnow',
    bgGradientDay: 'from-slate-600 via-blue-700 to-indigo-900',
    bgGradientNight: 'from-slate-950 via-slate-900 to-blue-950',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-indigo-200',
    isRainy: false,
    isSnowy: true,
    isSevere: false,
  },
  75: {
    label: 'Heavy Snow',
    description: 'Substantial snow accumulation',
    iconName: 'Snowflake',
    bgGradientDay: 'from-slate-700 via-slate-800 to-blue-950',
    bgGradientNight: 'from-slate-950 via-blue-950 to-black',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-sky-200',
    isRainy: false,
    isSnowy: true,
    isSevere: true,
  },
  77: {
    label: 'Snow Grains',
    description: 'Tiny icy frozen snow particles',
    iconName: 'Snowflake',
    bgGradientDay: 'from-slate-600 via-cyan-700 to-slate-900',
    bgGradientNight: 'from-slate-950 via-cyan-950 to-slate-900',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-cyan-200',
    isRainy: false,
    isSnowy: true,
    isSevere: false,
  },
  80: {
    label: 'Slight Rain Showers',
    description: 'Passing light showers',
    iconName: 'CloudRain',
    bgGradientDay: 'from-blue-500 via-slate-600 to-indigo-800',
    bgGradientNight: 'from-slate-900 via-blue-950 to-slate-950',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-sky-300',
    isRainy: true,
    isSnowy: false,
    isSevere: false,
  },
  81: {
    label: 'Moderate Rain Showers',
    description: 'Intermittent heavy showers',
    iconName: 'CloudRain',
    bgGradientDay: 'from-blue-600 via-slate-700 to-indigo-900',
    bgGradientNight: 'from-slate-950 via-blue-950 to-slate-900',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-sky-300',
    isRainy: true,
    isSnowy: false,
    isSevere: false,
  },
  82: {
    label: 'Violent Rain Showers',
    description: 'Downpours with heavy winds',
    iconName: 'CloudRainWind',
    bgGradientDay: 'from-slate-800 via-blue-900 to-slate-950',
    bgGradientNight: 'from-slate-950 via-black to-slate-950',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-blue-300',
    isRainy: true,
    isSnowy: false,
    isSevere: true,
  },
  85: {
    label: 'Slight Snow Showers',
    description: 'Brief light snow flurries',
    iconName: 'CloudSnow',
    bgGradientDay: 'from-slate-600 via-blue-700 to-slate-900',
    bgGradientNight: 'from-slate-950 via-slate-900 to-black',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-sky-200',
    isRainy: false,
    isSnowy: true,
    isSevere: false,
  },
  86: {
    label: 'Heavy Snow Showers',
    description: 'Intense snow squalls',
    iconName: 'Snowflake',
    bgGradientDay: 'from-slate-700 via-indigo-900 to-slate-950',
    bgGradientNight: 'from-slate-950 via-indigo-950 to-black',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-sky-200',
    isRainy: false,
    isSnowy: true,
    isSevere: true,
  },
  95: {
    label: 'Thunderstorm',
    description: 'Thunder and lightning expected',
    iconName: 'CloudLightning',
    bgGradientDay: 'from-slate-800 via-purple-900 to-slate-950',
    bgGradientNight: 'from-slate-950 via-purple-950 to-black',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-purple-300',
    isRainy: true,
    isSnowy: false,
    isSevere: true,
  },
  96: {
    label: 'Thunderstorm with Hail',
    description: 'Severe storm with small hail',
    iconName: 'CloudLightning',
    bgGradientDay: 'from-slate-800 via-indigo-950 to-black',
    bgGradientNight: 'from-slate-950 via-slate-950 to-black',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-amber-300',
    isRainy: true,
    isSnowy: true,
    isSevere: true,
  },
  99: {
    label: 'Heavy Hail Thunderstorm',
    description: 'Dangerous storm with heavy hail',
    iconName: 'CloudLightning',
    bgGradientDay: 'from-slate-900 via-purple-950 to-black',
    bgGradientNight: 'from-black via-purple-950 to-black',
    cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
    textColor: 'text-red-300',
    isRainy: true,
    isSnowy: true,
    isSevere: true,
  },
};

export function getWeatherCondition(code: number): WeatherConditionInfo {
  return (
    WMO_CODES[code] || {
      label: 'Unknown',
      description: 'Variable atmospheric conditions',
      iconName: 'Cloud',
      bgGradientDay: 'from-slate-600 to-slate-800',
      bgGradientNight: 'from-slate-900 to-slate-950',
      cardTheme: 'bg-white/10 backdrop-blur-md border-white/20',
      textColor: 'text-slate-200',
      isRainy: false,
      isSnowy: false,
      isSevere: false,
    }
  );
}
